# Stage 1: Build the React app in Node.js
FROM node:20

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory in the container
COPY package.json ./


# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory in the container
COPY . .

# Build the React app
RUN npm run build

# Use a different parent image to serve the React app
FROM nginx:alpine

# Copy the build output to the Nginx HTML directory
COPY --from=0 /app/build /usr/share/nginx/html

# Expose the port the app runs on
EXPOSE 80

# Command to run the application
CMD ["nginx", "-g", "daemon off;"]
