# Use an official Node.js runtime as a parent image
FROM node:20

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory in the container
COPY package.json ./


# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory in the container
COPY . .

# Expose the port the app runs on
EXPOSE 3003

# Command to run the application
CMD ["node", "server.js"]
